### ISSUE TITLE
CREATE FAILED error while using firecamp template

### ISSUE THREAD

**Issue by yogeshsajanikar** [aws-quickstart/quickstart-cloudstax-firecamp#14] opened 2018-03-19 12:13 UTC
I am continuously getting this error while deploying the cloud formation template for firecamp.

> Embedded stack arn:aws:cloudformation:ap-southeast-1:397377118507:stack/traderwave-firecamp-VPCStack-DB078ZU5GVF1/c3c18770-2b6d-11e8-ad4f-500c336f5a56 was not successfully created: The following resource(s) failed to create: [PrivateSubnet3ARouteTableAssociation, NAT1EIP, NAT2EIP, PublicSubnet1RouteTableAssociation, NAT3EIP, PublicSubnet3RouteTableAssociation, PrivateSubnet2ARouteTableAssociation, PublicSubnetRoute, PrivateSubnet1ARouteTableAssociation, PublicSubnet2RouteTableAssociation]

**Comment by JuniusLuo** [comment] 2018-03-20 18:02
The failure is at the VPC stack creation. We had a similar issue from another customer, [AWS QuickStart Failing at VPC Stack](https://github.com/cloudstax/firecamp/issues/43). The root cause for that issue was "api limits on that account". Could you please check the detail errors in the VPC template stack?

The stack was probably deleted, could set the filter to "Deleted" on CloudFormation Console to list all deleted stacks.
![image](https://user-images.githubusercontent.com/28828038/37673650-fdaaffa0-2c2d-11e8-9143-7a8339970dbe.png)

**Comment by JuniusLuo** [comment] 2018-03-22 05:45
@yogeshsajanikar Did you get a chance to check the VPC stack failure?

**Comment by yogeshsajanikar** [comment] 2018-03-22 06:02
I am yet tocheck, get back to you today!

**Comment by JuniusLuo** [comment] 2018-03-22 06:06
Thanks!

**Comment by JuniusLuo** [comment] 2018-04-17 02:51
Close the issue. @yogeshsajanikar if you hit it again, please feel free to reopen it.

**Comment by yogeshsajanikar** [comment] 2018-04-17 02:54
Actually, it hit us again. Unfortunately, I wasn't able to work on it again due to other things.

**Comment by JuniusLuo** [comment] 2018-04-17 03:01
Thanks @yogeshsajanikar . If you hit again, let's leave it open. If you could get time to check the VPC stack failure, please share the details. Thanks!

**Comment by avattathil** [comment] 2018-12-13 03:32
Closing  (no further updates for reporter)

**Closed by avattathil** 2018-12-13 03:32 UTC
